//this file is generated by perl script mkurom.
//Do not edit under pain of losing your edits!
 
module ID__ 
 #(ua=4)
( 
      input logic [5:0] IR,
      output logic [ua-1:0] Uip 
            ); 
always_comb begin
  unique case (IR) inside
    6'b00_00_00 :  Uip = 6'd7 ;   // HALT 
    6'b00_00_01 :  Uip = 6'd8 ;   // NOP 
    6'b11_10_?? :  Uip = 6'd9 ;   // LOADI 
    6'b10_11_?? :  Uip = 6'd14 ;   // STORE 
    6'b00_00_11 :  Uip = 6'd20 ;   // JUMP 
    6'b10_10_?? :  Uip = 6'd24 ;   // LOAD 
    6'b00_00_10 :  Uip = 6'd31 ;   // LOADBPR 
    6'b00_01_0? :  Uip = 6'd36 ;   // SETPG 
    6'b01_??_?? :  Uip = 6'd38 ;   // MOV 
    6'b11_01_?? :  Uip = 6'd41 ;   // ADDI 
    6'b10_01_?? :  Uip = 6'd48 ;   // ADD 
    default:      Uip = 6'd6 ;   // #UD fault 
  endcase
end
endmodule  // ID__ 
